// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssbnhniqxdrsaqwjesdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzYm5obmlxeGRyc2Fxd2plc2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDE5NTAsImV4cCI6MjA3MDAxNzk1MH0.1Xve-hdszjR1QXZbY9X_DQPDKJyeReLXxOtAliC83fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});